import { Providers } from './providers';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

function Providers({ children }: { children: React.ReactNode }) {
  return (
    <ChakraProvider>
      <DefaultLayout>{children}</DefaultLayout>
    </ChakraProvider>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
